"""initial schema — five core tables (Phase 1)

Hand-written (not autogenerated): Alembic can't introspect/emit CRDB's VECTOR type,
so we control the DDL directly. UUID PKs default to gen_random_uuid().

Revision ID: 0001
Revises:
Create Date: 2026-07-01
"""

from typing import Sequence, Union

import sqlalchemy as sa
from alembic import op

from app.config import get_settings
from app.types_crdb import Vector

revision: str = "0001"
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None

_UUID_PK = dict(server_default=sa.text("gen_random_uuid()"), primary_key=True)
_TS = sa.DateTime(timezone=True)


def upgrade() -> None:
    op.create_table(
        "agents",
        sa.Column("id", sa.Uuid(), nullable=False, **_UUID_PK),
        sa.Column("generation", sa.Integer(), nullable=False),
        sa.Column("bloodline", sa.Text(), nullable=False),
        sa.Column("status", sa.Text(), nullable=False),
        sa.Column("spawned_at", _TS, nullable=False),
        sa.Column("retired_at", _TS, nullable=True),
        sa.Column("parent_id", sa.Uuid(), nullable=True),
        sa.ForeignKeyConstraint(["parent_id"], ["agents.id"]),
    )
    op.create_index("ix_agents_bloodline_gen", "agents", ["bloodline", "generation"])

    op.create_table(
        "beliefs",
        sa.Column("id", sa.Uuid(), nullable=False, **_UUID_PK),
        sa.Column("rule_text", sa.Text(), nullable=False),
        sa.Column("originating_agent_id", sa.Uuid(), nullable=False),
        sa.Column("formed_at", _TS, nullable=False),
        sa.Column("embedding", Vector(get_settings().embedding_dim), nullable=True),
        sa.Column("status", sa.Text(), nullable=False, server_default=sa.text("'active'")),
        sa.Column("invalidated_at", _TS, nullable=True),
        sa.Column("invalidated_by", sa.Uuid(), nullable=True),
        sa.ForeignKeyConstraint(["originating_agent_id"], ["agents.id"]),
    )
    op.create_index("ix_beliefs_originating_agent", "beliefs", ["originating_agent_id"])

    op.create_table(
        "belief_inheritance",
        sa.Column("id", sa.Uuid(), nullable=False, **_UUID_PK),
        sa.Column("belief_id", sa.Uuid(), nullable=False),
        sa.Column("from_agent_id", sa.Uuid(), nullable=False),
        sa.Column("to_agent_id", sa.Uuid(), nullable=False),
        sa.Column("inherited_at", _TS, nullable=False),
        sa.ForeignKeyConstraint(["belief_id"], ["beliefs.id"]),
        sa.ForeignKeyConstraint(["from_agent_id"], ["agents.id"]),
        sa.ForeignKeyConstraint(["to_agent_id"], ["agents.id"]),
    )
    # Deposition query filters by to_agent_id; lineage query filters by belief_id.
    op.create_index("ix_bi_to_agent", "belief_inheritance", ["to_agent_id"])
    op.create_index("ix_bi_belief", "belief_inheritance", ["belief_id"])

    op.create_table(
        "decisions",
        sa.Column("id", sa.Uuid(), nullable=False, **_UUID_PK),
        sa.Column("agent_id", sa.Uuid(), nullable=False),
        sa.Column("txn_ref", sa.Text(), nullable=False),
        sa.Column("merchant", sa.Text(), nullable=False),
        sa.Column("amount", sa.Numeric(), nullable=False),
        sa.Column("verdict", sa.Text(), nullable=False),
        sa.Column("driving_belief_id", sa.Uuid(), nullable=True),
        sa.Column("confidence", sa.Float(), nullable=False),
        sa.Column("decided_at", _TS, nullable=False),
        sa.Column("is_fraud", sa.Boolean(), nullable=False),
        sa.ForeignKeyConstraint(["agent_id"], ["agents.id"]),
        sa.ForeignKeyConstraint(["driving_belief_id"], ["beliefs.id"]),
    )

    op.create_table(
        "belief_performance",
        sa.Column("id", sa.Uuid(), nullable=False, **_UUID_PK),
        sa.Column("belief_id", sa.Uuid(), nullable=False),
        sa.Column("window_start", _TS, nullable=False),
        sa.Column("window_end", _TS, nullable=False),
        sa.Column("confidence", sa.Float(), nullable=False),
        sa.Column("false_positive_rate", sa.Float(), nullable=False),
        sa.Column("frauds_approved", sa.Integer(), nullable=False),
        sa.ForeignKeyConstraint(["belief_id"], ["beliefs.id"]),
    )


def downgrade() -> None:
    op.drop_table("belief_performance")
    op.drop_table("decisions")
    op.drop_index("ix_bi_belief", table_name="belief_inheritance")
    op.drop_index("ix_bi_to_agent", table_name="belief_inheritance")
    op.drop_table("belief_inheritance")
    op.drop_index("ix_beliefs_originating_agent", table_name="beliefs")
    op.drop_table("beliefs")
    op.drop_index("ix_agents_bloodline_gen", table_name="agents")
    op.drop_table("agents")
